version: '3.7'
services:
  db:
    image: postgres:15
    container_name: booking_db_app
    env_file:
      - .env-non-dev
    ports:
      - 5432:5432

  redis:
    image: redis:7
    container_name: booking_redis

  booking:
    image: booking_image
    build:
      context: .
    container_name: booking_app
    env_file:
      - .env-non-dev
    command: [ "/booking_app/docker/app.sh" ]
    ports:
      - 8888:8000
    depends_on:
      - db
      - redis
  celery:
    build:
      context: .
    container_name: booking_celery
    env_file:
      - .env-non-dev
    command: [ "/booking_app/docker/celery.sh", "celery" ]
    depends_on:
      - redis
      - db

  flower:
    build:
      context: .
    container_name: booking_flower
    command: [ "/booking_app/docker/celery.sh", "flower" ]
    env_file:
      - .env-non-dev
    depends_on:
      - redis
      - celery
    ports:
      - 5555:5555

  prometheus:
    image: prom/prometheus:v2.43.0
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheusdata:/prometheus
    restart: unless-stopped
    ports:
      - 9090:9090

  grafana:
    image: grafana/grafana:9.4.7
    container_name: grafana
    volumes:
      - grafanadata:/var/lib/grafana
    restart: unless-stopped
    ports:
      - 3000:3000

volumes:
  grafanadata:
  prometheusdata:

networks:
  aiofast_default:
    external: true
